# Generated by Django 2.2.3 on 2021-05-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_text',
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
